name: cm_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  logger: ^2.2.0
  flutter_flavor: ^3.1.3
  flex_color_scheme: ^7.3.1
  cached_network_image: ^3.3.1

dev_dependencies: 
  flutter_lints: 3.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

